// Generated by PARAKH — load this before dashboard.html's script.
window.PARAKH_DATA = {
  "meta" : {
    "engine" : "PARAKH",
    "jobTitle" : "Senior AI Engineer — Founding Team @ Redrob AI",
    "totalScored" : 100000,
    "honeypotsRejected" : 5634,
    "topShown" : 10,
    "topReturned" : 100
  },
  "top" : [ {
    "rank" : 1,
    "candidateId" : "CAND_0077337",
    "score" : 0.7729,
    "base" : 0.9069999999999999,
    "reasoning" : "Staff Machine Learning Engineer @ Paytm, 7.0 yrs. On-target ranking/retrieval title, 15 IR/ML signals in work history. 10 trusted role-relevant skill(s). 2/4 product roles, NLP/IR domain. Active 32d ago, response 95%, open-to-work, notice 60d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 15 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.85,
      "weighted" : 0.17,
      "multiplier" : false,
      "evidence" : "10 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "7.0 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.7,
      "weighted" : 0.105,
      "multiplier" : false,
      "evidence" : "2/4 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India, will relocate"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.9999999999999999,
      "weighted" : 0.09999999999999999,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 68; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.85215,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 32d ago, response 95%, open-to-work, notice 60d"
    } ]
  }, {
    "rank" : 2,
    "candidateId" : "CAND_0079387",
    "score" : 0.749357,
    "base" : 0.9000199999999999,
    "reasoning" : "AI Engineer @ Microsoft, 6.9 yrs. On-target ranking/retrieval title, 17 IR/ML signals in work history. 8 trusted role-relevant skill(s). 2/4 product roles, NLP/IR domain. Active 63d ago, response 81%, open-to-work, notice 30d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 17 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.8651000000000002,
      "weighted" : 0.17302000000000006,
      "multiplier" : false,
      "evidence" : "8 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "6.9 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.7,
      "weighted" : 0.105,
      "multiplier" : false,
      "evidence" : "2/4 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.8999999999999999,
      "weighted" : 0.09,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 64; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.8326,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 63d ago, response 81%, open-to-work, notice 30d"
    } ]
  }, {
    "rank" : 3,
    "candidateId" : "CAND_0081846",
    "score" : 0.74911,
    "base" : 0.94133,
    "reasoning" : "Lead AI Engineer @ Razorpay, 6.7 yrs. On-target ranking/retrieval title, 19 IR/ML signals in work history. 9 trusted role-relevant skill(s). 2/2 product roles, NLP/IR domain. Active 55d ago, response 73%, open-to-work, notice 30d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 19 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.8624,
      "weighted" : 0.17248000000000002,
      "multiplier" : false,
      "evidence" : "9 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "6.7 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 1.0,
      "weighted" : 0.15,
      "multiplier" : false,
      "evidence" : "2/2 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India, will relocate"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.8684999999999999,
      "weighted" : 0.08685,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 34; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.7958000000000001,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 55d ago, response 73%, open-to-work, notice 30d"
    } ]
  }, {
    "rank" : 4,
    "candidateId" : "CAND_0064326",
    "score" : 0.738883,
    "base" : 0.8715499999999999,
    "reasoning" : "Search Engineer @ Sarvam AI, 7.6 yrs. On-target ranking/retrieval title, 10 IR/ML signals in work history. 6 trusted role-relevant skill(s). 1/4 product roles, NLP/IR domain. Active 37d ago, response 94%, open-to-work, notice 45d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 10 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.7452500000000001,
      "weighted" : 0.14905000000000002,
      "multiplier" : false,
      "evidence" : "6 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "7.6 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.55,
      "weighted" : 0.0825,
      "multiplier" : false,
      "evidence" : "1/4 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "in preferred Indian metro"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.8999999999999999,
      "weighted" : 0.09,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 61; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.84778,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 37d ago, response 94%, open-to-work, notice 45d"
    } ]
  }, {
    "rank" : 5,
    "candidateId" : "CAND_0046525",
    "score" : 0.73778,
    "base" : 0.8980236111111111,
    "reasoning" : "Senior Machine Learning Engineer @ Genpact AI, 6.1 yrs. On-target ranking/retrieval title, 14 IR/ML signals in work history. 4 trusted role-relevant skill(s). 1/2 product roles, NLP/IR domain. Active 35d ago, response 88%, open-to-work, notice 60d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 14 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.7733680555555555,
      "weighted" : 0.1546736111111111,
      "multiplier" : false,
      "evidence" : "4 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "6.1 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.7,
      "weighted" : 0.105,
      "multiplier" : false,
      "evidence" : "1/2 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "in preferred Indian metro"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.8835,
      "weighted" : 0.08835,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 37; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.82156,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 35d ago, response 88%, open-to-work, notice 60d"
    } ]
  }, {
    "rank" : 6,
    "candidateId" : "CAND_0011687",
    "score" : 0.735512,
    "base" : 0.8459999999999999,
    "reasoning" : "Senior NLP Engineer @ Niramai, 7.8 yrs. On-target ranking/retrieval title, 13 IR/ML signals in work history. 6 trusted role-relevant skill(s). 0/2 product roles, NLP/IR domain. Active 48d ago, response 89%, open-to-work, notice 15d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 13 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.82,
      "weighted" : 0.164,
      "multiplier" : false,
      "evidence" : "6 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "7.8 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.4,
      "weighted" : 0.06,
      "multiplier" : false,
      "evidence" : "0/2 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.8999999999999999,
      "weighted" : 0.09,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 76; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.8694000000000001,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 48d ago, response 89%, open-to-work, notice 15d"
    } ]
  }, {
    "rank" : 7,
    "candidateId" : "CAND_0046064",
    "score" : 0.732007,
    "base" : 0.8939999999999999,
    "reasoning" : "Senior NLP Engineer @ Salesforce, 8.9 yrs. On-target ranking/retrieval title, 20 IR/ML signals in work history. 7 trusted role-relevant skill(s). 2/3 product roles, NLP/IR domain. Active 62d ago, response 78%, open-to-work, notice 30d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 20 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.835,
      "weighted" : 0.167,
      "multiplier" : false,
      "evidence" : "7 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 0.85,
      "weighted" : 0.085,
      "multiplier" : false,
      "evidence" : "8.9 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.8,
      "weighted" : 0.12,
      "multiplier" : false,
      "evidence" : "2/3 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.8999999999999999,
      "weighted" : 0.09,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 67; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.8188000000000001,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 62d ago, response 78%, open-to-work, notice 30d"
    } ]
  }, {
    "rank" : 8,
    "candidateId" : "CAND_0002025",
    "score" : 0.731124,
    "base" : 0.8829999999999999,
    "reasoning" : "Senior AI Engineer @ Apple, 5.9 yrs. On-target ranking/retrieval title, 13 IR/ML signals in work history. 8 trusted role-relevant skill(s). 1/2 product roles, NLP/IR domain. Active 32d ago, response 80%, open-to-work, notice 30d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 13 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.805,
      "weighted" : 0.16100000000000003,
      "multiplier" : false,
      "evidence" : "8 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 0.85,
      "weighted" : 0.085,
      "multiplier" : false,
      "evidence" : "5.9 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.7,
      "weighted" : 0.105,
      "multiplier" : false,
      "evidence" : "1/2 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.9999999999999999,
      "weighted" : 0.09999999999999999,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 97; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.8280000000000001,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 32d ago, response 80%, open-to-work, notice 30d"
    } ]
  }, {
    "rank" : 9,
    "candidateId" : "CAND_0036184",
    "score" : 0.721412,
    "base" : 0.8254144444444443,
    "reasoning" : "Recommendation Systems Engineer @ CRED, 6.0 yrs. On-target ranking/retrieval title, 10 IR/ML signals in work history. 8 trusted role-relevant skill(s). 1/2 product roles, NLP/IR domain. Active 32d ago, response 90%, open-to-work, notice 30d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 10 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.8340722222222222,
      "weighted" : 0.16681444444444446,
      "multiplier" : false,
      "evidence" : "8 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "6.0 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 0.7,
      "weighted" : 0.105,
      "multiplier" : false,
      "evidence" : "1/2 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 0.82,
      "weighted" : 0.082,
      "multiplier" : false,
      "evidence" : "in India"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.21600000000000003,
      "weighted" : 0.021600000000000005,
      "multiplier" : false,
      "evidence" : "github 43;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.874,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 32d ago, response 90%, open-to-work, notice 30d"
    } ]
  }, {
    "rank" : 10,
    "candidateId" : "CAND_0018499",
    "score" : 0.717641,
    "base" : 0.969,
    "reasoning" : "Senior Machine Learning Engineer @ Zomato, 7.2 yrs. On-target ranking/retrieval title, 17 IR/ML signals in work history. 10 trusted role-relevant skill(s). 3/3 product roles, NLP/IR domain. Active 45d ago, response 61%, open-to-work, notice 15d.",
    "components" : [ {
      "name" : "CareerRelevance",
      "weight" : 0.35,
      "raw" : 1.0,
      "weighted" : 0.35,
      "multiplier" : false,
      "evidence" : "on-target ranking/retrieval title, 17 IR/ML signals in work history"
    }, {
      "name" : "SkillTrust",
      "weight" : 0.2,
      "raw" : 0.845,
      "weighted" : 0.169,
      "multiplier" : false,
      "evidence" : "10 trusted role-relevant skill(s)"
    }, {
      "name" : "ExperienceFit",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "7.2 yrs vs 6–8 ideal (5–9 band)"
    }, {
      "name" : "DomainProduct",
      "weight" : 0.15,
      "raw" : 1.0,
      "weighted" : 0.15,
      "multiplier" : false,
      "evidence" : "3/3 product roles, NLP/IR domain"
    }, {
      "name" : "Location",
      "weight" : 0.1,
      "raw" : 1.0,
      "weighted" : 0.1,
      "multiplier" : false,
      "evidence" : "in preferred Indian metro"
    }, {
      "name" : "EvalSignal",
      "weight" : 0.1,
      "raw" : 0.9999999999999999,
      "weighted" : 0.09999999999999999,
      "multiplier" : false,
      "evidence" : "eval-framework literate; github 95; relevant nice-to-haves;"
    }, {
      "name" : "Disqualifier",
      "weight" : 0.0,
      "raw" : 1.0,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "no disqualifiers fired"
    }, {
      "name" : "Availability",
      "weight" : 0.0,
      "raw" : 0.7405999999999999,
      "weighted" : 0.0,
      "multiplier" : true,
      "evidence" : "active 45d ago, response 61%, open-to-work, notice 15d"
    } ]
  } ],
  "honeypots" : [ {
    "candidateId" : "CAND_0000011",
    "reason" : "skill 'Kubeflow' duration 59mo exceeds total experience 24mo"
  }, {
    "candidateId" : "CAND_0000017",
    "reason" : "claims 12.3y experience but only 9y since college began (2017)"
  }, {
    "candidateId" : "CAND_0000056",
    "reason" : "skill 'BentoML' duration 48mo exceeds total experience 16mo"
  }, {
    "candidateId" : "CAND_0000090",
    "reason" : "skill 'MLOps' duration 50mo exceeds total experience 20mo"
  }, {
    "candidateId" : "CAND_0000177",
    "reason" : "claims 12.2y experience but only 10y since college began (2016)"
  }, {
    "candidateId" : "CAND_0000194",
    "reason" : "skill 'MLOps' duration 47mo exceeds total experience 22mo"
  }, {
    "candidateId" : "CAND_0000202",
    "reason" : "skill 'Forecasting' duration 59mo exceeds total experience 32mo"
  }, {
    "candidateId" : "CAND_0000230",
    "reason" : "skill 'MLOps' duration 57mo exceeds total experience 23mo"
  }, {
    "candidateId" : "CAND_0000234",
    "reason" : "skill 'Hugging Face Transformers' duration 45mo exceeds total experience 17mo"
  }, {
    "candidateId" : "CAND_0000256",
    "reason" : "skill 'Weights & Biases' duration 59mo exceeds total experience 28mo"
  }, {
    "candidateId" : "CAND_0000318",
    "reason" : "claims 12.1y experience but only 10y since college began (2016)"
  }, {
    "candidateId" : "CAND_0000340",
    "reason" : "claims 11.7y experience but only 9y since college began (2017)"
  }, {
    "candidateId" : "CAND_0000376",
    "reason" : "claims 14.2y experience but only 11y since college began (2015)"
  }, {
    "candidateId" : "CAND_0000411",
    "reason" : "skill 'MLOps' duration 59mo exceeds total experience 34mo"
  }, {
    "candidateId" : "CAND_0000435",
    "reason" : "claims 14.9y experience but only 9y since college began (2017)"
  }, {
    "candidateId" : "CAND_0000439",
    "reason" : "claims 13.5y experience but only 11y since college began (2015)"
  }, {
    "candidateId" : "CAND_0000444",
    "reason" : "claims 14.3y experience but only 8y since college began (2018)"
  }, {
    "candidateId" : "CAND_0000462",
    "reason" : "skill 'Diffusion Models' duration 56mo exceeds total experience 25mo"
  }, {
    "candidateId" : "CAND_0000467",
    "reason" : "skill 'PEFT' duration 53mo exceeds total experience 26mo"
  }, {
    "candidateId" : "CAND_0000470",
    "reason" : "claims 14.2y experience but only 9y since college began (2017)"
  }, {
    "candidateId" : "CAND_0000491",
    "reason" : "claims 14.1y experience but only 9y since college began (2017)"
  }, {
    "candidateId" : "CAND_0000504",
    "reason" : "claims 14.8y experience but only 10y since college began (2016)"
  }, {
    "candidateId" : "CAND_0000507",
    "reason" : "skill 'Time Series' duration 55mo exceeds total experience 14mo"
  }, {
    "candidateId" : "CAND_0000541",
    "reason" : "claims 11.6y experience but only 7y since college began (2019)"
  }, {
    "candidateId" : "CAND_0000542",
    "reason" : "claims 12.9y experience but only 8y since college began (2018)"
  }, {
    "candidateId" : "CAND_0000591",
    "reason" : "claims 12.1y experience but only 9y since college began (2017)"
  }, {
    "candidateId" : "CAND_0000617",
    "reason" : "skill 'Sentence Transformers' duration 50mo exceeds total experience 17mo"
  }, {
    "candidateId" : "CAND_0000625",
    "reason" : "skill 'Weights & Biases' duration 59mo exceeds total experience 34mo"
  }, {
    "candidateId" : "CAND_0000628",
    "reason" : "skill 'Qdrant' duration 53mo exceeds total experience 25mo"
  }, {
    "candidateId" : "CAND_0000652",
    "reason" : "skill 'Reinforcement Learning' duration 52mo exceeds total experience 25mo"
  } ]
};
