package com.parakh.io;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.parakh.engine.ComponentScore;
import com.parakh.engine.RankedCandidate;
import com.parakh.engine.RankingEngine;
import org.springframework.stereotype.Service;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Optional, side-channel output for the explainability dashboard. Emits a single browser-loadable
 * file ({@code window.PARAKH_DATA = {...};}) so {@code dashboard.html} renders the score-component
 * breakdown of the top candidates and the honeypot-rejection log straight off the filesystem — no
 * server, no network. This NEVER touches {@code submission.csv}; the contest output is unchanged
 * whether or not a dashboard path is supplied.
 */
@Service
public class DashboardWriter {

    /** How many ranked candidates to surface in the breakdown chart. */
    private static final int TOP_FOR_CHART = 10;

    private final ObjectMapper json = new ObjectMapper();

    public void write(Path out, RankingEngine.Result result) {
        Map<String, Object> root = new LinkedHashMap<>();

        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("engine", "PARAKH");
        meta.put("jobTitle", "Senior AI Engineer — Founding Team @ Redrob AI");
        meta.put("totalScored", result.totalScored());
        meta.put("honeypotsRejected", result.honeypotsRejected());
        meta.put("topShown", Math.min(TOP_FOR_CHART, result.top().size()));
        meta.put("topReturned", result.top().size());
        root.put("meta", meta);

        List<Map<String, Object>> top = new ArrayList<>();
        int rank = 1;
        for (RankedCandidate rc : result.top()) {
            if (rank > TOP_FOR_CHART) break;
            Map<String, Object> row = new LinkedHashMap<>();
            row.put("rank", rank++);
            row.put("candidateId", rc.candidateId());
            row.put("score", rc.score());
            row.put("base", rc.base());
            row.put("reasoning", rc.reasoning());
            List<Map<String, Object>> comps = new ArrayList<>();
            for (ComponentScore c : rc.components()) {
                Map<String, Object> cm = new LinkedHashMap<>();
                cm.put("name", c.name());
                cm.put("weight", c.weight());
                cm.put("raw", c.raw());
                cm.put("weighted", c.weighted());
                cm.put("multiplier", c.multiplier());
                cm.put("evidence", c.evidence());
                comps.add(cm);
            }
            row.put("components", comps);
            top.add(row);
        }
        root.put("top", top);

        List<Map<String, Object>> honeypots = new ArrayList<>();
        for (RankingEngine.HoneypotHit h : result.honeypotSample()) {
            Map<String, Object> hm = new LinkedHashMap<>();
            hm.put("candidateId", h.candidateId());
            hm.put("reason", h.reason());
            honeypots.add(hm);
        }
        root.put("honeypots", honeypots);

        try (BufferedWriter w = Files.newBufferedWriter(out, StandardCharsets.UTF_8)) {
            w.write("// Generated by PARAKH — load this before dashboard.html's script.\n");
            w.write("window.PARAKH_DATA = ");
            w.write(json.writerWithDefaultPrettyPrinter().writeValueAsString(root));
            w.write(";\n");
        } catch (IOException e) {
            throw new RuntimeException("Failed writing dashboard data to " + out + ": " + e.getMessage(), e);
        }
    }
}
